name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    uses: matt-riley/matt-riley-ci/.github/workflows/nvim-format.yml@1ec59196c8788655c59455d00c3a7c41c2ef12f3 # main
