name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    uses: matt-riley/matt-riley-ci/.github/workflows/nvim-tests.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce # main
