name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    uses: matt-riley/matt-riley-ci/.github/workflows/nvim-tests.yml@cc060a6749be6869154f21c6b3463a1ca218e2e3 # main
